sudo: required
language: minimal
services:
  - docker
env:
  matrix:
    secure: N8eGAamaM5lzw1njNJDlE1bG1KgJ1YrmVan2Nws/ik1ZG9Iuig8QTb/3ydeiM7NAkWDJONN7VZuGZ2pKY4m1BkBmptwC9f2KAMgbOIB6lWNbyKpqEjRFfJDpLmT5zJ7vzj+Ho3VlacJMJQEIsHacsyOTchAqAjDT6C7wVTAk7OYh5p+TP/YrbOOvdb6bQOm0vg8Yq88qQMj3/mNEvNaF286wODVOcyYXd+HA4dmx1G1IAzAtzYfWx/QXy5kraGtO7YCLdRkw1NCT6nMu2nEFekmj5ckldS/Vwfv5AZGB6+p0+d70ZqhytHoYtj2oM/nu2xnim7Oy775/55ez1hJKDv3M0JRIlq79nTYBWmnCXfST6UmI8zxlUEd2eiA1811346Y7pKDU9cLmVlqRSEBHX9xda1GQZlnsXBty+wNG900qcxnsaCgOoI2H+WP2Z8ffK1mhITxgVXbJFz7Rr7owS1MdKwmp6kdWirnWPAbeiDjESvkaMTK4jnyKnQ+51vh4z/MZwISoNiREA+mO58YHsKW3U/S+cpr1LRU+LE9Zs81lVdGaicYSIEHeCY7B4okEy4zrejUyLEU/0BURoXdQnvRdaFzPEx40E9wujh+vrv4elwU9eBjZPJ2LoVS2J4i4qfFmvIr6YRXUvKYAR76oa9Qd8+PxSJwreElGnVeMhPY=
install:
- wget -O $HOME/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64" && chmod 700 $HOME/hadolint
script: ./build.sh
