sudo: false
env:
  matrix:
    secure: Caow0qKkX7jtJVL1LhAaXOKvffK/jkydIFTWnc28LD/JPdmhgT8qZ2IbnnWrocCJ55J4GKmWkdf5WZ5hNobKYNwCbeVv6Je2MEYMkKsTfJKuglbXDJY0NMKJ/d9SUCDxLeTCSjiwuD4PhZV+F18Eoyps6v2dzJ8BspuRisVaQCWFLGJVlDvs7eN91TRDy25hV5aXMEygv90CFANIhofAOTPfF82YRUe8kinKaHPKn33/nagt/Z/RsvCtKqWWITB6DZOSHHTNmKnq2Rn/oYH7AsTUtlXzVsUcg8LK1CdXtjqEFtYYfNYj3nZnUsNvyLt5GhUPLo3rd6BxRD+LVPEZ8CLoyqUPrY8Z2xxptKE3L/5N1uX3/Ozd0eiTcSDdtIJGWfi+gPCnBA7lafBoF/wkINF3nhU20iy0o6fJODYFl6gcZxBggSu71bWH7z5CAzOP0vRB60iLlMtVF6vjIC+TEJ5x2MITXcznaZ2FBlH4X2HCboB5cqrTFauP98PrTqtlaScD/g6dgCm+ridU8TnLg2Olq8ySY4ishEG+l3cJJZuT8Dvp0wG7wRQcGC4AkiudeSew4X7sWkDnFQItfZF0XzDhbAoEu2lzsFOuvUGIAiah/A/YHJ5b6LNShlSR/0uqgoZuluATE+ZmmYjjhsRPmUQ3DBYHq0naLfJpIQiyP+A=
install:
- wget -O /bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.6.5/hadolint-Linux-x86_64" && chmod 700 /bin/hadolint
script: build.sh
